### ISSUE TITLE
Kick

### ISSUE THREAD

**Issue by Monke220** [Turqee/th-bot#4]
command to auto kick someone saying really bad stuff like N word  and F word and also CP. so yeah

also make certain roles unkickable just incase

**Comment by zTheroy** [comment]
There are a ton of bots that do that already, like probot or mee6. Also the cp one wouldn't work, because it would need a reference image and we don't want to be searching that, do we? Also it can't kick anyone (for now)

**Comment by zTheroy** [comment]
Still good intentions though

**Comment by Therqy** [comment]
kick command almost done lets gooooooooooooooooooo

**Comment by Therqy** [comment]
ok so

**Comment by specters312** [comment]
lol
